### ISSUE TITLE
Project Scanning Crash

### ISSUE THREAD

**Issue by Jborhi** [eumario/godot-manager#10]
**Describe the bug**
Upon scanning for projects, program crashes.

**To Reproduce**
1.Launch program
2.Click "Scan Projects"
3.Program Crashes

and

1.Launch Program
2.Go to settings and click projects
3.Tick "Scan each time Godot Manager is Launched"
4.Close program
5.Upon relaunch, program immediately crashes

**Expected behavior**
Project files are scanned into program

**OS and Program Version**
 - OS: Windows 10
 - Version 0.1.1

**Additional context**
Project folder contains nested folders

**Comment by eumario** [comment]
Could you tell me what is in Settings > Projects > Directories to Scan list?

**Comment by RevonZev** [comment]
The cause seems to be that the program trying to scan a folder that doesn't exist.
How I recreate the problem:
Create a folder and edit the "Directories to scan" to that folder and erase the folder.
The default path value is "Documents\Project" which the user probably doesn't have.

My suggestion:
A popup when clicked the scan button to select what folder to scan when "Directories to scan" is empty and made "Directories to scan" empty as default.

**Comment by Jborhi** [comment]
> The cause seems to be that the program trying to scan a folder that doesn't exist.
> 
> **How I recreate the problem:**
> Create a folder and edit the "Directories to scan" to that folder and erase the folder.
> The default path value is "Documents\Project" which the user probably doesn't have.

I second that idea as my directories to scan is the default "Documents\Projects" and no such directory exists for me.

**Comment by eumario** [comment]
I had a feeling that it may be because there is no such folder to scan.  So I will fix that.
