### ISSUE TITLE
Add assets without asset library

### ISSUE THREAD

**Issue by GammaGames** [eumario/godot-manager#20]
**Is your feature request related to a problem? Please describe.**
It's more of an enhancement to the current asset management features (GOOD WORK), since HungryProton's [Scatter](https://github.com/HungryProton/scatter) plugin isn't on the asset library.

**Describe the solution you'd like**
The ability to add assets as a zip file (Scatter's documentation makes it look [that easy](https://github.com/HungryProton/scatter/wiki/Installation-and-basic-setup)). 

**Describe alternatives you've considered**
Managing it myself? Ew!  
It would also be nice to add a github repo and to grab the files on the latest release since Scatter is just a "drop source code in addons folder" release. That would be a bit more work than a zip file though, and might not work for other repos.

**Additional context**
Is this import button supposed to do anything? 
![image](https://user-images.githubusercontent.com/7832163/166118784-2fabbded-239b-427a-aed0-a885c711d60b.png)
I thought that would let me import a zip file, but no such luck.

**Comment by eumario** [comment]
Yes, the Import button is supposed to be for importing a Zip file, or Folder as an Addon asset, so that you can develop our own addons, and be able to test and see that they work correctly.  I held off on that for the moment, while I was working on getting Tuxfamily Mirror stuff going, as that is needed.  So, in v0.2, you'll more then likely see a different manager for Plugins, that'll allow you to use Github to import and version plugins, importing from local folders / zip files, and utilizing the Asset Library, along with something else that I can't reveal at the moment, as there are things in discussion behind the scenes that will be interesting if everything bears fruit.
