### ISSUE TITLE
Cyrillic alphabet is not supported

### ISSUE THREAD

**Issue by Teashrock** [eumario/godot-manager#21]
**Describe the bug**
Any text written with Cyrillic alphabet just simply won't be displayed. Instead it just displays empty spaces and nothingness.

**To Reproduce**
1. Go to any text input field.
2. Try to type any Cyrillic text.
3. See nothing.

**Expected behavior**
1. Write Cyrillic text anywhere.
2. See it being displayed properly.

**Screenshots**
The folder chosen below is called Зображення, meaning Pictures (please note how the path is specified in the text field):
![image](https://user-images.githubusercontent.com/12483854/167860132-90ca6ca8-fe8d-4f8b-83c6-9781f5859742.png)

Now we're inside this folder, please note the slash symbol at the end of the string, as well as file names (this dangling whitespace on each file separates words Знімок екрану, both of which are not displayed:
![image](https://user-images.githubusercontent.com/12483854/167861998-14300429-c369-440f-99da-8407c42f3fb5.png)

This also happens with the default path, which should be "/home/username/Documents/Projects". But my Documents folder is named Документи, resulting in just not being displayed at all in the text string:
![image](https://user-images.githubusercontent.com/12483854/167861601-31a6f75e-d993-45bd-b531-c22f97063a69.png)

**Complete the Following:**
 - OS: Ubuntu Linux x86_64
 - Version: Focal Fossa 20.04

**Additional context**
The probable solution: change the font to the one supporting not only Latin characters, but other alphabets as well.

**Comment by eumario** [comment]
This is a dual problem with the code and fonts.  The first part, being that the font I am using is Droid Sans, which is a non-standard, stripped version for English only text.  I have a new version of the font that will support other languages, that I will be adding to the update in the future, which should solve the issue.

The second, is that I have no translated strings stored anywhere in the project at this point and time, and I need to either figure out, or create a system in which to create the translation strings, and setup the default English Dictionary, so that I can properly provide them for translators to translate into different languages.  I will be working on this as well.
